source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'MissingAnchors_Example' do
  pod "MissingAnchors", :path => "../"
  pod "MissingAnchors/NSLayoutAnchor", :path => "../"
end

target 'MissingAnchors_Tests' do
  pod "MissingAnchors", :path => "../"
  pod "MissingAnchors/NSLayoutAnchor", :path => "../"
end
